version: '3.8'
services:
  immich-slideshow:
    container_name: immich_slideshow
    image: persistentcloud/immich-slideshow
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
      # no_cache: true
    ports:
      - "8780:80"
    volumes:
      - ./public/config.json:/usr/share/nginx/html/config.json:ro
    